### ISSUE TITLE
C#: `Error_Collection` is not generated to C#

### ISSUE THREAD

**Issue by texastony** [smithy-lang/smithy-dafny#37]
We introduced an un-modeled Error structure, `Error_Collection`.
We currently only [generate in Dafny code](https://github.com/awslabs/polymorph/blob/763e6c265258ab78bf02a96f59c8fd22b2d8f335/smithy-polymorph/src/main/java/software/amazon/polymorph/smithydafny/DafnyApiCodegen.java#L1137-L1160).

But we should also generate a C# allegory and conversion logic for this.

**Comment by robin-aws** [comment]
There is potentially a deeper issue here: the `CollectionOfErrors` concept, like opaque errors, is not modeled at the Smithy level, so it's hard to know what the idiomatic representation of it is in a given target language.

**Comment by texastony** [comment]
This has been addressed via https://github.com/smithy-lang/smithy-dafny/pull/262
